const assert = require('node:assert/strict');
const fs = require('node:fs');
const src = fs.readFileSync(`${__dirname}/../TodoDoc.js`, 'utf8').replace('.pragma library', '');
const T = new Function(`${src}; return {parse,setChecked,setTaskText,removeTask,makeSubtask,appendTask};`)();
const crlf = '# List\r\n- [ ]no gap\r\n- [X] Done\r\n';
assert.equal(T.parse(crlf).length, 2);
assert.equal(T.setChecked(crlf, 1, true), crlf.replace('[ ]', '[x]'));
assert.equal(T.setTaskText(crlf, 1, 'edited'), crlf.replace('no gap', 'edited'));
assert.equal(T.appendTask(crlf, 'new').text, crlf + '- [ ] new\r\n');
assert.equal(T.appendTask('# Title', 'new').text, '# Title\n- [ ] new');
assert.equal(T.removeTask('- [ ] a\n- [ ] b', 1), '- [ ] a\n');
assert.equal(T.makeSubtask('- [ ] a\r\n* [X] b\r\n', 1), '- [ ] a\r\n  * [X] b\r\n');
const yaml = '\uFEFF---\n- [ ] yaml\n...\n- [ ] actual\n';
assert.deepEqual(T.parse(yaml).map(t => t.text), ['actual']);
assert.equal(T.setChecked(yaml, 1, true), null);
const fences = '````md\n```\n~~~\n- [ ] example\n````\n- [ ] actual\n';
assert.deepEqual(T.parse(fences).map(t => t.text), ['actual']);
assert.equal(T.removeTask(fences, 3), null);
assert.equal(T.appendTask('```md\nexample\n', 'new'), null);
assert.equal(T.appendTask('---\ntitle: unfinished\n', 'new'), null);
console.log('Markdown: line endings, YAML, fence matching and byte preservation passed');
